### ISSUE TITLE
Support overwritting `external-ui` and `external-controller`

### ISSUE THREAD

**Issue by felinae98** [spencerwooo/clashrup#22]

**Comment by spencerwooo** [comment]
This is already supported.

https://github.com/spencerwooo/clashrup/blob/0dedac760e2c8c372d55a2415b8a77eeb36381a6/src/config.rs#L187-L197

https://github.com/spencerwooo/clashrup/blob/0dedac760e2c8c372d55a2415b8a77eeb36381a6/src/config.rs#L33-L35
