### ISSUE TITLE
[help wanted] How to choose the node of the proxy

### ISSUE THREAD

**Issue by 0x404** [spencerwooo/clashrup#62]
Thank you very much for creating this tool. I found it very useful, but I have a question: I don't know how to choose the node of the proxy.

**Comment by spencerwooo** [comment]
The Clash external controller API can be used for controlling Clash. The port to expose this RESTful API can be set and overwritten with `clashrup`. After which, you can use third party web-based Clash dashboards (such as [yacd](https://github.com/haishanh/yacd)) to control Clash remotely.
